services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    networks:
      default:
        ipv4_address: 10.5.0.10
    volumes:
      - "./traefik:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.rule: "Host(`traefik.k8s.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      traefik.http.routers.api.entrypoints: "https"
      traefik.http.routers.api.service: "api@internal"
      traefik.http.routers.api.tls: "true"
      traefik.http.routers.api.tls.options: "default"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    command:
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.filename=/etc/traefik/certificates.yml"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https=true"
      - "--entrypoints.https.address=:443"
      - "--log=true"
      - "--log.level=DEBUG"
      # API & Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"
