services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    userns_mode: "host"
    volumes:
      - "./traefik:/etc/traefik"
      - "/run/user/1000/podman/podman.sock:/var/run/docker.sock"
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.rule: "Host(`traefik.k8s.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      traefik.http.routers.api.entrypoints: "https"
      traefik.http.routers.api.service: "api@internal"
      traefik.http.routers.api.tls: "true"
      traefik.http.routers.api.tls.options: "default"
    ports:
      - "8080:8080/tcp"
      - "8443:8443/tcp"
      - "8443:8443/udp"
    command:
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.filename=/etc/traefik/certificates.yml"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:8080"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https=true"
      - "--entrypoints.https.address=:8443"
      - "--log=true"
      - "--log.level=DEBUG"
      # API & Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"
