apiVersion: v1
clusters:
  - cluster:
      server: ""
    name: talos-default
contexts:
  - context:
      cluster: talos-default
      user: admin@talos-default
    name: admin@talos-default
current-context: admin@talos-default
kind: Config
preferences: {}
users:
  - name: admin@talos-default
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://authelia.k8s.localhost
          - --oidc-client-id=kube_login
          - --oidc-client-secret=insecure_secret
          - --oidc-extra-scope=groups
          - --insecure-skip-tls-verify=true
        command: kubectl
        env: null
        provideClusterInfo: false
