[tools]
java = "temurin"
k3d = "latest"
mkcert = "latest"
node = "lts"
rust = { version = "latest", profile = "default", components = "rust-src,llvm-tools" }
talosctl = "latest"
task = "latest"
yarn = "latest"

[env]
MISE_NODE_COREPACK = "true"
