[package]
name = "server"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
utoipa = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
kube = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }

utoipa-actix-web = { workspace = true }

opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry-appender-tracing = { workspace = true }
tracing-subscriber = { workspace = true }

utoipa-scalar = { version = "0.3", features = ["actix-web"] }
actix-cors = { version = "0.7" }
tracing-actix-web = { git = "https://github.com/asonix/tracing-actix-web", branch = "asonix/opentelemetry-0-31", features = [
    "opentelemetry_0_31",
] }

api = { path = "../../libs/api" }
trace = { path = "../../libs/trace" }
common = { path = "../../libs/common" }
controller = { path = "../../libs/controller" }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
