# Give default service account the rights needed to read Custom Resource Definitions
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-sa-crd-reader
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
# Create ClusterRole 'crd-reader' to allow reading CRDs
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-reader
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "weebo.si.rs"
    resources:
      - "proxykubeapis"
    verbs:
      - get
      - list
      - watch
