[package]
name = "kubectl_proxyauth"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = "4.5.53"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
